# -*- coding: utf-8 -*-
"""Пайплайн.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mF0OPJuMpVLjmYcS5EHELKgybi2qr6zn

#**Пайплайн для прогнозирования трафика для четырех перекрестков**

Горизонт прогнозирования: 1-5 часов в зависимости от перекрестка.


Формат входных данных: name.csv с такими параметрами:


* 4 колонки: DateTime, Junction, Vehicles, ID. Тип DateTime: object. У остальных float. Без нулей/Nan и пропусков.


Адрес данных для проверки работоспособности пайплайна:
https://raw.githubusercontent.com/MVRonkin/TimeSeriesCourse/fd0f3aeec3bfe81887226bc668e4e1a7cefb0dd2/OLD%20Versions/2026/datasets/Traffic%20Prediction/traffic.csv


- Для активации запустить ячейку, подождать и ввести адрес файла.

---
"""

# ==================== 1. Импорт библиотек ====================
import pandas as pd
import numpy as np

!pip install statsforecast==1.6.0
!pip install statsforecast utilsforecast
from statsforecast import StatsForecast
import statsmodels
from statsforecast.models import ARIMA, ETS

!pip install mlforecast
from mlforecast import MLForecast
from mlforecast.target_transforms import Differences
from lightgbm import LGBMRegressor

!pip install neuralforecast
from neuralforecast import NeuralForecast
from neuralforecast.models import NHITS

import warnings
warnings.filterwarnings('ignore')

# ==================== 2. Вспомогательные функции ====================

def validate_data(file_path):
    """Проверяет, что файл существует и содержит обязательные столбцы."""
    try:
        df = pd.read_csv(file_path, nrows=0)
    except Exception as e:
        raise ValueError(f"Ошибка чтения файла: {e}")

    required_cols = ['DateTime', 'Junction', 'Vehicles']
    for col in required_cols:
        if col not in df.columns:
            raise ValueError(f"Отсутствует обязательный столбец: {col}")

    print("Файл валиден: содержит все необходимые столбцы.")
    return True

def load_and_prepare_data(file_path):
    """Загружает данные и преобразует в формат панельных данных."""
    df = pd.read_csv(file_path)
    df['DateTime'] = pd.to_datetime(df['DateTime'])
    df = df.drop('ID', axis=1)
    df = df.rename(columns={'DateTime': 'ds', 'Junction': 'unique_id', 'Vehicles': 'y'})
    df['unique_id'] = df['unique_id'].astype(str)
    df = df.sort_values(['unique_id', 'ds']).reset_index(drop=True)
    return df

def train_and_predict(df, horizon=5):
    """
    Обучает модели и возвращает прогнозы на horizon часов.
    """
    # ETS
    sf_ets = StatsForecast(models=[ETS(season_length=24)], freq='H', n_jobs=-1)
    sf_ets.fit(df)
    ets_pred = sf_ets.predict(h=horizon).reset_index()
    ets_pred = ets_pred.rename(columns={'ETS': 'y_hat'})
    if 'unique_id' not in ets_pred.columns:
        ets_pred = ets_pred.rename(columns={ets_pred.columns[0]: 'unique_id'})

    # NHITS
    nf = NeuralForecast(models=[NHITS(h=horizon, input_size=48, max_steps=100)], freq='H')
    nf.fit(df)
    nhits_pred = nf.predict().reset_index().rename(columns={'NHITS': 'y_hat'})
    if 'unique_id' not in nhits_pred.columns:
        nhits_pred = nhits_pred.rename(columns={nhits_pred.columns[0]: 'unique_id'})

    # LightGBM
    mlf = MLForecast(
        models=[LGBMRegressor(verbosity=-1)],
        freq='H',
        lags=[1, 2, 3, 4, 5, 6, 12, 24],
        target_transforms=[Differences([1])]
    )
    mlf.fit(df)
    lgb_pred = mlf.predict(h=horizon).rename(columns={'LGBMRegressor': 'y_hat'})

    # ARIMA(1,1,1)
    sf_arima = StatsForecast(models=[ARIMA(order=(1,1,1))], freq='H', n_jobs=-1)
    sf_arima.fit(df)
    arima_pred = sf_arima.predict(h=horizon).reset_index().rename(columns={'ARIMA': 'y_hat'})
    if 'unique_id' not in arima_pred.columns:
        arima_pred = arima_pred.rename(columns={arima_pred.columns[0]: 'unique_id'})

    forecasts = {
        'ETS': ets_pred,
        'NHITS': nhits_pred,
        'LightGBM': lgb_pred,
        'ARIMA': arima_pred
    }
    return forecasts

# ==================== 3. Основной пайплайн ====================
def run_pipeline(file_path):
    # 1. Проверка данных
    validate_data(file_path)

    # 2. Загрузка и подготовка
    df = load_and_prepare_data(file_path)

    # 3. Обучение и прогноз на 5 часов
    forecasts = train_and_predict(df, horizon=5)

    # 4. Соответствие моделей перекрёсткам
    model_for_junction = {
        1: 'ETS',
        2: 'NHITS',
        3: 'ETS',
        4: 'ARIMA'
    }

    # 5. Количество часов для вывода
    hours_map = {1: 5, 2: 5, 3: 4, 4: 1}

    # 6. Формирование таблицы прогнозов
    table_data = []
    for uid in sorted(df['unique_id'].unique()):
        uid_int = int(uid)
        model_name = model_for_junction.get(uid_int, 'ETS')
        pred_df = forecasts[model_name]
        uid_pred = pred_df[pred_df['unique_id'] == uid].sort_values('ds')
        n_hours = hours_map.get(uid_int, 0)
        if n_hours > 0:
            pred_vals = uid_pred['y_hat'].iloc[:n_hours].values
            if len(pred_vals) < 5:
                pred_vals = list(pred_vals) + ['нет данных'] * (5 - len(pred_vals))
            table_data.append([uid_int] + pred_vals)
        else:
            table_data.append([uid_int] + ['нет данных'] * 5)

    columns = ['№ Перекрестка'] + [f'Прогноз на {i+1} час' for i in range(5)]
    forecast_table = pd.DataFrame(table_data, columns=columns)
    print('\n=== Таблица прогнозов ===')
    print(forecast_table.to_string(index=False))

# ==================== 4. Запуск пайплайна ====================
if __name__ == '__main__':
    file_path = input("Введите путь к файлу данных (CSV): ").strip()
    if (file_path.startswith("'") and file_path.endswith("'")) or (file_path.startswith('"') and file_path.endswith('"')):
        file_path = file_path[1:-1]
    run_pipeline(file_path)